Patch ZeChrale's raids
Noctem/pokeminer pull request #324
Opened 2017-07-11 11:57 UTC by MonkeyTedBaker

Fixed bugs present in ZeChrales/Monocle raids branch.
Tested and running fine with > 30,000rpm of hashkeys at full capacity.

_Fixes applied only on backend._

2017-07-12 12:25 UTC, evenly-epic-mule requested changes
I haven't tested it but some small things I noticed

2017-07-12 12:25 UTC, evenly-epic-mule commented on monocle/sanitized.py
> +	'RAIDS_FILTER': (1, 2, 3, 4, 5),
tab

and I'd guess filtering on (3,4,5) by default would be better

2017-07-12 12:25 UTC, evenly-epic-mule commented on monocle/static/css/main.css
> +	height: 32px;
tab

2017-07-12 12:25 UTC, evenly-epic-mule commented on monocle/static/js/main.js
> +monitor(overlays.Workers, true)
why change this?

2017-07-12 12:25 UTC, evenly-epic-mule commented on monocle/worker.py
>              'prestige': raw.gym_points,
is that still provided or can it be removed?
note: if you remove it there may be places where it is accessed without checking the availability

2017-07-12 12:43 UTC, Zoruk commented on monocle/db.py
> +            f.slots_available
`f.slots_available` -> `fs.slots_available`

2017-07-12 13:57 UTC, phonezawphyo commented on monocle/sanitized.py
> +	'RAIDS_FILTER': (1, 2, 3, 4, 5),
Will set 3,4,5 as suggested

2017-07-12 13:57 UTC, phonezawphyo commented on monocle/static/js/main.js
> +monitor(overlays.Workers, true)
accident xD

2017-07-12 13:58 UTC, phonezawphyo commented on monocle/worker.py
>              'prestige': raw.gym_points,
Will leave it for legacy reasons. Somebody should make a separate PR to remove prestige.

2017-07-12 13:58 UTC, phonezawphyo commented on monocle/db.py
> +            f.slots_available
Thanks. Lifesaver.

2017-07-12 14:25 UTC, MonkeyTedBaker commented on monocle/sanitized.py
> +	'RAIDS_FILTER': (1, 2, 3, 4, 5),
Will set 3,4,5 as suggested

2017-07-12 14:26 UTC, MonkeyTedBaker commented on monocle/db.py
> +            f.slots_available
Thanks. Lifesaver.

2017-07-12 14:26 UTC, MonkeyTedBaker commented on monocle/worker.py
>              'prestige': raw.gym_points,
Will leave it for legacy reasons. Somebody should make a separate PR to remove prestige.

2017-07-12 14:26 UTC, MonkeyTedBaker commented on monocle/static/js/main.js
> +monitor(overlays.Workers, true)
accident xD

2017-07-13 13:21 UTC, Zoruk commented on monocle/web_utils.py
> +                .filter(Fort.external_id == fort_id) \
`Fort.external_id == fort_id` => `Fort.id == fort_id`

2017-07-13 13:24 UTC, Zoruk commented
Can you also provide the icons? They're not in the official icons repo

2017-07-14 01:26 UTC, MonkeyTedBaker commented on monocle/web_utils.py
> +                .filter(Fort.external_id == fort_id) \
Thanks.

2017-07-14 01:27 UTC, MonkeyTedBaker commented
@Zoruk I only intend to implement backend (as I don't use the frontend myself). However, I've added raid icons for convenience of testers. Thank you.

2017-07-19 20:34 UTC, tmagnier commented on monocle/static/css/main.css
> +    height: 30x;
height: 30**p**x;

2017-07-26 19:35 UTC, MrCanan commented
Is it possible to add the "WebHook" feature to allow receiving egg and raid notifications on PokeAlarm ? =)

2017-07-30 19:49 UTC, MrCanan commented
Can you add Raids to webhook to be able to have notifications ? =)

2017-08-02 00:46 UTC, MonkeyTedBaker commented
There you go. Raid notifications.

2017-08-02 22:12 UTC, mfaalk commented
Would it be possible to show all defending pokémons instead of just the last one entered at the frontend?
It would be great if you can display CP of the pokémon and maybe even trainer name.

2017-08-03 19:15 UTC, MrCanan commented
Hi MonkeyTedBaker,

Thanks to have add Raids Notifications. =)

But their is an error with PokeAlarm webhook : 
`2017-08-02 16:04:53,239 [    "niceraids"][   Manager][   ERROR] Encountered error during processing: TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime'`

It seems their is a missing parameter to send to webhook : `raid_begin`, so normally simply add `data['message']['raid_begin'] = pokemon['time_spawn']` just before the line `'data['message']['disappear_time'] = ts`
And the line : `'data['message']['disappear_time'] = ts` should be replace with : `'data['message']['raid_end'] = ts`
But, you will understand this problem and find a solution faster than me. =)

Very cordially.

2017-08-04 04:35 UTC, MonkeyTedBaker commented
@MrCanan Since it is adding only 2 extra parameters, I've added it to the raid web hook. 
If the web hook format is much more different, it would advise you to ask for PokeAlarm to support this format.
Haven't tested it with PokeAlarm since I don't use it.

@mfaalk Yes but not in this branch. Im doing it in another branch of mine, gymplus. It's still heavily in WIP and not recommended to pull it.

2017-08-11 13:20 UTC, MonkeyTedBaker commented
For those who would enjoy extra gym info for this version of raids, I've made another pull request with all the juicy details #350

2017-08-24 09:20 UTC, MonkeyTedBaker commented
Better version offered in #350

2017-08-24 09:20 UTC, closed without merging